on: 
  schedule: 
    - cron: '0 0 * * 0'
  workflow_dispatch: 

name: 'acr/quarkus/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $REGION ]]; then
          export REGION=northcentralus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          if [[ -z $ACR_NAME ]]; then
          export ACR_NAME=acreg$RANDOM
          fi
          az acr create \
          --name $ACR_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true
          
          cd acr/quarkus
          
          mvn package
          export ACR_QUARKUS_IMAGE=quarkus:latest
          
          az acr build --registry $ACR_NAME --resource-group $RESOURCE_GROUP --image $ACR_QUARKUS_IMAGE .
          
          cd ../..
          
          
          export RESULT=$(az acr repository show --name $ACR_NAME --image $ACR_QUARKUS_IMAGE)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ -z $RESULT ]]; then
          echo "Unable to find $ACR_QUARKUS_IMAGE image"
          exit 1
          fi