on: 
  schedule: 
    - cron: '0 18 * * 1'
  workflow_dispatch: 

name: 'afd/create-endpoint/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=northcentralus
          echo "Using 'northcentralus' region"
          fi
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $AFD_PROFILE_NAME ]]; then
          export AFD_PROFILE_NAME=javazafd$RANDOM
          fi
          az afd profile create \
          --profile-name $AFD_PROFILE_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku Premium_AzureFrontDoor
          
          if [[ -z $AFD_ENDPOINT_NAME ]]; then
          export AFD_ENDPOINT_NAME=javazafdendp$RANDOM
          fi
          az afd endpoint create \
          --resource-group $RESOURCE_GROUP \
          --endpoint-name $AFD_ENDPOINT_NAME \
          --profile-name $AFD_PROFILE_NAME \
          --enabled-state Enabled
          
          export RESULT=$(az afd endpoint show --endpoint-name $AFD_ENDPOINT_NAME --profile-name $AFD_PROFILE_NAME --resource-group $RESOURCE_GROUP --output tsv --query provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          echo "Azure Front Door Endpoint $AFD_ENDPOINT_NAME was not provisioned properly"
          exit 1
          fi