on: 
  schedule: 
    - cron: '0 0 * * 5'
  workflow_dispatch: 

name: 'afd/create-origin-group/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
      - uses: 'actions/checkout@v3'
      - run: |
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joaz-rg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $AFD_PROFILE_NAME ]]; then
          export AFD_PROFILE_NAME=javazafd$RANDOM
          fi
          az afd profile create \
          --profile-name $AFD_PROFILE_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku Premium_AzureFrontDoor
          
          if [[ -z $AFD_ENDPOINT_NAME ]]; then
          export AFD_ENDPOINT_NAME=javazafdendp$RANDOM
          fi
          az afd endpoint create \
          --resource-group $RESOURCE_GROUP \
          --endpoint-name $AFD_ENDPOINT_NAME \
          --profile-name $AFD_PROFILE_NAME \
          --enabled-state Enabled
          
          if [[ -z $AFD_ORIGIN_GROUP_NAME ]]; then
          export AFD_ORIGIN_GROUP_NAME=javazafdogrp$RANDOM
          fi
          az afd origin-group create \
          --resource-group $RESOURCE_GROUP \
          --origin-group-name $AFD_ORIGIN_GROUP_NAME \
          --profile-name $AFD_PROFILE_NAME \
          --probe-request-type GET \
          --probe-protocol Http \
          --probe-interval-in-seconds 60 \
          --probe-path / \
          --sample-size 4 \
          --successful-samples-required 3 \
          --additional-latency-in-milliseconds 50
          
          export RESULT=$(az afd origin-group show --origin-group-name $AFD_ORIGIN_GROUP_NAME --profile-name $AFD_PROFILE_NAME --resource-group $RESOURCE_GROUP --output tsv --query provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          echo "Azure Front Door Origin Group $AFD_ORIGIN_GROUP_NAME was not provisioned properly"
          exit 1
          fi
permissions: 
  contents: 'read'
  id-token: 'write'