on: 
  schedule: 
    - cron: '0 0 * * 1'
  workflow_dispatch: 

name: 'afd/create-profile/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
      - uses: 'actions/checkout@v3'
      - run: |
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joazrg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $AFD_PROFILE_NAME ]]; then
          export AFD_PROFILE_NAME=javazafd$RANDOM
          fi
          az afd profile create \
          --profile-name $AFD_PROFILE_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku Premium_AzureFrontDoor
          
          export RESULT=$(az afd profile show --profile-name $AFD_PROFILE_NAME --resource-group $RESOURCE_GROUP --output tsv --query provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          echo "Azure Front Door Profile $AFD_PROFILE_NAME was not provisioned properly"
          exit 1
          fi
permissions: 
  contents: 'read'
  id-token: 'write'