on: 
  schedule: 
    - cron: '0 0 * * 4'
  workflow_dispatch: 

name: 'appservice/jboss-eap-helloworld/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
      - uses: 'actions/checkout@v3'
      - run: |
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joaz-rg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $APPSERVICE_PLAN ]]; then
          export APPSERVICE_PLAN=javazappsvcplan-$RANDOM
          fi
          
          az appservice plan create \
          --resource-group $RESOURCE_GROUP \
          --location $REGION \
          --name $APPSERVICE_PLAN \
          --is-linux \
          --sku P1v3
          
          cd appservice/jboss-eap-helloworld
          
          mvn clean package
          export APPSERVICE_JBOSS_EAP_HELLOWORLD=appservice-jboss-eap-helloworld-$RANDOM
          
          mvn azure-webapp:deploy \
          -DappName=$APPSERVICE_JBOSS_EAP_HELLOWORLD \
          -DappServicePlan=$APPSERVICE_PLAN \
          -DresourceGroup=$RESOURCE_GROUP
          
          sleep 240
          cd ../..
          
          
          export RESULT=$(az webapp show --resource-group $RESOURCE_GROUP --name $APPSERVICE_JBOSS_EAP_HELLOWORLD --output tsv --query state)
          if [[ "$RESULT" != Running ]]; then
          echo 'Web application is NOT running'
          az group delete --name $RESOURCE_GROUP --yes || true
          exit 1
          fi
          export URL=https://$(az webapp show --resource-group $RESOURCE_GROUP --name $APPSERVICE_JBOSS_EAP_HELLOWORLD --output tsv --query defaultHostName)
          export RESULT=$(curl $URL)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != *"Hello World"* ]]; then
          echo "Response did not contain 'Hello World'"
          exit 1
          fi
permissions: 
  contents: 'read'
  id-token: 'write'