on: 
  schedule: 
    - cron: '0 17 * * 5'
  workflow_dispatch: 

name: 'appservice/jboss-eap-helloworld/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $REGION ]]; then
          export REGION=northcentralus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          if [[ -z $APPSERVICE_PLAN ]]; then
          export APPSERVICE_PLAN=appservice-plan-$RANDOM
          export REGION=northcentralus
          fi
          az appservice plan create \
          --resource-group $RESOURCE_GROUP \
          --location $REGION \
          --name $APPSERVICE_PLAN \
          --is-linux \
          --sku P1v3
          
          cd appservice/jboss-eap-helloworld
          
          mvn clean package
          export APPSERVICE_JBOSS_EAP_HELLOWORLD=appservice-jboss-eap-helloworld-$RANDOM
          
          mvn azure-webapp:deploy \
          -DappName=$APPSERVICE_JBOSS_EAP_HELLOWORLD \
          -DappServicePlan=$APPSERVICE_PLAN \
          -DresourceGroup=$RESOURCE_GROUP
          
          sleep 240
          cd ../..
          
          
          export RESULT=$(az webapp show --resource-group $RESOURCE_GROUP --name $APPSERVICE_JBOSS_EAP_HELLOWORLD --output tsv --query state)
          if [[ "$RESULT" != Running ]]; then
          echo 'Web application is NOT running'
          az group delete --name $RESOURCE_GROUP --yes || true
          exit 1
          fi
          export URL=https://$(az webapp show --resource-group $RESOURCE_GROUP --name $APPSERVICE_JBOSS_EAP_HELLOWORLD --output tsv --query defaultHostName)
          export RESULT=$(curl $URL)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != *"Hello World"* ]]; then
          echo "Response did not contain 'Hello World'"
          exit 1
          fi