on: 
  schedule: 
    - cron: '0 17 * * 3'
  workflow_dispatch: 

name: 'cognitiveservices/create-openai-account/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
      - uses: 'actions/checkout@v3'
      - run: |
          
          if [[ -z $REGION ]]; then
          export REGION=eastus
          fi
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joaz-rg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          export COG_AZURE_OPENAI_NAME=cog-$RANDOM
          
          az cognitiveservices account create \
          --name $COG_AZURE_OPENAI_NAME \
          --resource-group $RESOURCE_GROUP \
          --location eastus \
          --kind OpenAI \
          --sku S0 \
          --yes
          
          export RESULT=$(az cognitiveservices account show --name $COG_AZURE_OPENAI_NAME --resource-group $RESOURCE_GROUP --output tsv --query properties.provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          echo "Azure OpenAI account " $COG_AZURE_OPENAI_NAME " was not created successfully"
          exit 1
          fi
permissions: 
  contents: 'read'
  id-token: 'write'