on: 
  schedule: 
    - cron: '0 21 * * 2'
  workflow_dispatch: 

name: 'cosmosdb/create-sql-database/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
      - uses: 'actions/checkout@v3'
      - run: |
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joazrg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $COSMOSDB_ACCOUNT_NAME ]]; then
          export COSMOSDB_ACCOUNT_NAME=cosmosdb-$RANDOM
          az cosmosdb create \
          --name $COSMOSDB_ACCOUNT_NAME \
          --resource-group $RESOURCE_GROUP \
          --locations regionName=eastus failoverPriority=0
          fi
          
          
          if [[ -z $COSMOSDB_SQL_DATABASE ]]; then
          export COSMOSDB_SQL_DATABASE=sql-database-$RANDOM
          az cosmosdb sql database create \
          --resource-group $RESOURCE_GROUP \
          --account-name $COSMOSDB_ACCOUNT_NAME \
          --name $COSMOSDB_SQL_DATABASE
          fi
          
          
          export RESULT=$(az cosmosdb sql database show \
          --resource-group $RESOURCE_GROUP \
          --account-name $COSMOSDB_ACCOUNT_NAME \
          --name $COSMOSDB_SQL_DATABASE \
          --output tsv --query id)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" == "" ]]; then
          echo "Failed to create CosmosDB SQL database $COSMOSDB_SQL_DATABASE"
          exit 1
          fi
permissions: 
  contents: 'read'
  id-token: 'write'