on: 
  schedule: 
    - cron: '0 14 * * 1'
  workflow_dispatch: 

name: 'servicebus/receive-jms-message/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'actions/setup-java@v4'
        with: 
          java-version: '17'
          distribution: 'temurin'
      - uses: 'azure/login@v1'
        with: 
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
      - uses: 'actions/checkout@v3'
      - run: |
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joazrg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          export SERVICE_BUS=joaz-sb-$RANDOM
          az servicebus namespace create \
          --resource-group $RESOURCE_GROUP \
          --name $SERVICE_BUS \
          --sku Premium \
          --location $REGION
          if [[ -z $SERVICE_BUS_QUEUE ]]; then
          export SERVICE_BUS_QUEUE=service-bus-queue-$RANDOM
          fi
          az servicebus queue create \
          --resource-group $RESOURCE_GROUP \
          --namespace-name $SERVICE_BUS \
          --name $SERVICE_BUS_QUEUE
          export SERVICE_BUS_QUEUE_CONNECTION_STRING=$(az servicebus namespace authorization-rule keys list \
          --resource-group $RESOURCE_GROUP --namespace-name $SERVICE_BUS --name RootManageSharedAccessKey \
          --query primaryConnectionString --output tsv)
          
          cd servicebus/send-jms-message
          
          mvn clean package
          java -jar target/send-jms-message.jar
          
          cd ../..
          
          export SERVICE_BUS_QUEUE_CONNECTION_STRING=$(az servicebus namespace authorization-rule keys list \
          --resource-group $RESOURCE_GROUP --namespace-name $SERVICE_BUS --name RootManageSharedAccessKey \
          --query primaryConnectionString --output tsv)
          
          cd servicebus/receive-jms-message
          
          mvn clean package
          java -jar target/receive-jms-message.jar
          
          cd ../..
          
          
          export RESULT=$(az servicebus queue show --resource-group $RESOURCE_GROUP --namespace $SERVICE_BUS --name $SERVICE_BUS_QUEUE --query countDetails.activeMessageCount --output tsv)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != "0" ]]; then
          exit 1
          fi
permissions: 
  contents: 'read'
  id-token: 'write'