on: 
  schedule: 
    - cron: '0 15 * * 0'
  workflow_dispatch: 

name: 'storage/list-file-share/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
      - uses: 'actions/checkout@v3'
      - run: |
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joazrg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          export STORAGE_ACCOUNT_NAME=joazst$RANDOM
          
          az storage account create \
          --name $STORAGE_ACCOUNT_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku Standard_LRS \
          --kind StorageV2
          
          export STORAGE_ACCOUNT_CONNECTION_STRING=$(az storage account show-connection-string --resource-group $RESOURCE_GROUP --name $STORAGE_ACCOUNT_NAME --output tsv)
          export STORAGE_SHARE_NAME=joazshare$RANDOM
          
          az storage share create --name $STORAGE_SHARE_NAME --account-name $STORAGE_ACCOUNT_NAME
          
          cd storage/list-file-share
          export RESULT=$(java -jar target/list-file-share.jar
          cd ../..
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != *""* ]]; then
          echo "There are already files in your Azure File Share"
          exit 1
          fi
permissions: 
  contents: 'read'
  id-token: 'write'